spring.application.name=backup-management-system
server.port=${PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/backup_system}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Mysql@123}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

backup.encryption.secret=${BACKUP_ENCRYPTION_SECRET:ChangeThisToAStrongSecretKey123}

# JWT Configuration
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=86400000

# MySQL Binary Paths
backup.mysql.path=${MYSQL_PATH:C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql.exe}
backup.mysqldump.path=${MYSQLDUMP_PATH:C:\Program Files\MySQL\MySQL Server 8.0\bin\mysqldump.exe}

# Metadata database name (blocked from backup/restore operations)
backup.metadata.database=${BACKUP_METADATA_DATABASE:backup_meta}